### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by iqbalza** [AllanHasegawa/Tempo#1]
Hi, when will support for Java be available?

**Comment by AllanHasegawa** [comment]
I have no plans to support Java at this moment since I migrated all my projects to Kotlin.

I could, however, try to make a friendlier interface for Java? Not sure. Do you have any opinions on how this lib should  be used from Java?

**Comment by iqbalza** [comment]
Well I think an interface alone would be great!

**Comment by AllanHasegawa** [comment]
Closing this issue as I haven't used Java in any of my projects for more than 3 years now, and Kotlin is now the oficial programming language for Android. Therefore, I'll not be doing a Java version for this project.
