### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by petedoyle** [AllanHasegawa/Tempo#12]
Hi Allan, I'm close to being able to turn Jetifier off in my app and was curious if you'd be open to updating Tempo's Android support libs to use AndroidX? Happy to help with a CR if you're open to it.

**Comment by AllanHasegawa** [comment]
Hey Pete o/

I have some good news! I've been working for the past weeks re-doing the internals of the library, and one of the changes is completely removing the Support libs. This also means I'm removing AndroidJob completely, but should be fine.

Other changes include removing the RxJava dependency and using Coroutines instead.

**Comment by petedoyle** [comment]
Awesome, that's exciting! Will be watching. Thanks for a super useful library! :)

**Comment by Wrywulf** [comment]
@AllanHasegawa any chance you can do a minor/patch release just removing android support library deps? Seems like the removal of rxjava etc could be a bit of a bigger migration (with more risk).

If doing the source code changes is not fitting into your dev flow right now, perhaps you can just release a (temporary) 0.3.1 binary release using the 
`./jetifier-standalone -i  <tempo-0.3.0.aar> -o <tempo-0.3.1.aar>`

?

Just to remove the androidx support
