### ISSUE TITLE
Document proguard rules (if any)

### ISSUE THREAD

**Issue by skjolber** [AllanHasegawa/Tempo#17]
I'm obfuscating my application, and it would be helpful if the docs contained a note on the correct proguard configuration (or if no special configuration is requird).

**Comment by AllanHasegawa** [comment]
Thanks for opening an issue! 

Tempo shouldn't require any Proguard specific rules.

I'm using Tempo on a Proguarded app without any issues. I also went through the code to double check to see if the lib uses reflection or anything that could break under Proguard and I didn't find any issues.

I like the suggestion to add a note in the docs. I'll add it to the FAQ, thanks 👍
