### ISSUE TITLE
Some Questions and feature requests

### ISSUE THREAD

**Issue by kenneth-leong-gt** [AllanHasegawa/Tempo#20]
1) Is there ever a need to call `Tempo.stop()` ?
2) Is is possible to have a function to completely clear all currently scheduled work requests?
3) Can we have an api to add worker constraints to the `WorkManagerScheduler` e.g. below
```
val constraints = Constraints.Builder()
            .setRequiredNetworkType(NetworkType.CONNECTED)
            .setRequiresBatteryNotLow(true)
            .build()
```
4) Is there a need for `autoSyncConfig`, if i have already a `WorkManagerScheduler`?

**Comment by AllanHasegawa** [comment]
> 1. Is there ever a need to call `Tempo.stop()` ?

Not really, no. I personally am not calling it on my apps.


>     2. Is is possible to have a function to completely clear all currently scheduled work requests?

By work I guess you're talking about the `WorkManagerScheduler`, right? In that case, no. The Scheduler implementation for Tempo is quite simple at this moment.

>     3. Can we have an api to add worker constraints to the `WorkManagerScheduler` e.g. below

I don't have a need for it at this moment, but you can implement the Scheduler yourself, given how simple that process is. Check here:

https://github.dev/AllanHasegawa/Tempo/tree/master/tempo-android-workmanager-scheduler/src/main/java/io/tempo/schedulers/internal

Or, if you really want an API in the lib, feel free to open a PR.

>     4. Is there a need for `autoSyncConfig`, if i have already a `WorkManagerScheduler`?

They are two different sync mechanisms. `autoSyncConfig` is controlled by the app, so it needs the app to be running to execute. And it's very precise and guaranteed to run. Meanwhile, `WorkManagerScheduler` is controlled by the system and may not run at the given time.

I personally always run with `autoSyncConfig`, and leave `WorkManagerScheduler` as optional if users on your app may use the app while offline.

It's up to you to decide which sync strategy you need for your app.

**Comment by AllanHasegawa** [comment]
Closing for now. Feel free to reopen if you have anymore questions.
